name: hands-on-neuroai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pytest
  - ruff
  - pip
  - pip:
    - pytorch
    - torchvision
